repos:
  - repo: local
    hooks:
      - id: ruff-lint  # linting
        name: ruff-lint
        entry: ruff check
        args:
          [
            --force-exclude,
            --config,
            pyproject.toml,
            --fix,
            --show-fixes,
            --exit-non-zero-on-fix,
          ]
        language: system
        types_or: [python]
        require_serial: true # run once for all files
      - id: ruff-format  # formatting
        name: ruff-format
        entry: ruff format
        args: [--force-exclude, --config, pyproject.toml]
        language: system
        types_or: [python]
        require_serial: true # run once for all files
      - id: pyright  # type checking
        name: pyright
        entry: pyright
        language: system
        types: [python]
        require_serial: true # run once for all files
      - id: dprint  # TOML and Markdown formatting
        name: dprint
        entry: dprint fmt
        language: system
        types: [markdown]
        require_serial: true # run once for all files
        pass_filenames: false
